name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          name: frontend-devops
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# 1. Download artifact
# 2. Deploy to github pages

# Useful actions
#  dawidd6/action-download-artifact@v2
#  crazy-max/ghaction-github-pages@v3
