name: CI

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
      - run: npm ci
  lint:
    needs: [ install ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  test:
    needs: [ install ]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
      - run: npm ci
      - run: npm run test:ci
  build:
    needs: [ test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
      - run: npm ci
      - run: npm run build:ci
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-devops
          path: build








# Steps
# 1. Make sure dependencies are installed
#   - Optionally cache dependencies
# 2. Test and lint the application
#    - This can be run in parallel
# 3. If the testing and linting succeeds create production distribution
# 4. Upload the artifacts

# Create a separate workflow to deploy the app or add CD step here

# Useful actions
# actions/setup-node@v3
# actions/checkout@v3
# actions/setup-node@v3
# actions/upload-artifact@v3
